pool:
  name: default
  demands:
    - maven
    - Agent.Version -equals 2.163.1
stages:
  - stage: checkoutcode
    jobs: 
      - job: 'checkoutgitcode'
    pool:
      name: Default
      demands:
            - maven
            - Agent.Version -equals 2.164.1
      steps:
          - checkout: self
  - stage: 'Build'
    jobs:
      - job: 'Buildjob'
    pool:
      name: Default
      demands:
        - maven
        - Agent.Version -equals 2.164.1
      steps:
        - task: Maven@4
          inputs:
              mavenPomFile: 'pom.xml'
              goals: 'install'
              publishJUnitResults: false
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false