pool:
  name: default
stages:
  - stage: stageA
    jobs:
      - job: jobA
        steps:
          - task: Docker@2
             
  - stage: stageB
    condition: succeeded('A') 
    jobs:
      - job: jobB 

